/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkflowsIndexRouteImport } from './routes/app/workflows/index'
import { Route as AppIntegrationsIndexRouteImport } from './routes/app/integrations/index'
import { Route as AppCredentialsIndexRouteImport } from './routes/app/credentials/index'
import { Route as ApiWorkflowsIndexRouteImport } from './routes/api/workflows/index'
import { Route as ApiCredentialsIndexRouteImport } from './routes/api/credentials/index'
import { Route as AppWorkflowIdRouteImport } from './routes/app_.workflow/$id'
import { Route as AppWorkflowLayoutRouteImport } from './routes/app/workflow/_layout'
import { Route as ApiIntegrationsStatusRouteImport } from './routes/api/integrations/status'
import { Route as ApiCredentialsIdRouteImport } from './routes/api/credentials/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiWorkflowsIdIndexRouteImport } from './routes/api/workflows/$id/index'
import { Route as ApiWorkflowsIdTestRouteImport } from './routes/api/workflows/$id/test'
import { Route as ApiWebhooksTallyWorkflowIdRouteImport } from './routes/api/webhooks/tally.$workflowId'
import { Route as ApiWebhooksGenericWorkflowIdRouteImport } from './routes/api/webhooks/generic.$workflowId'
import { Route as ApiIntegrationsSlackDisconnectRouteImport } from './routes/api/integrations/slack.disconnect'
import { Route as ApiIntegrationsSlackConnectRouteImport } from './routes/api/integrations/slack.connect'
import { Route as ApiIntegrationsSlackChannelsRouteImport } from './routes/api/integrations/slack.channels'
import { Route as ApiIntegrationsSlackCallbackRouteImport } from './routes/api/integrations/slack.callback'
import { Route as ApiIntegrationsDiscordGuildsRouteImport } from './routes/api/integrations/discord.guilds'
import { Route as ApiIntegrationsDiscordDisconnectRouteImport } from './routes/api/integrations/discord.disconnect'
import { Route as ApiIntegrationsDiscordConnectRouteImport } from './routes/api/integrations/discord.connect'
import { Route as ApiIntegrationsDiscordChannelsRouteImport } from './routes/api/integrations/discord.channels'
import { Route as ApiIntegrationsDiscordCallbackRouteImport } from './routes/api/integrations/discord.callback'
import { Route as ApiCredentialsIdTestRouteImport } from './routes/api/credentials/$id.test'
import { Route as ApiWorkflowsIdExecutionsLatestRouteImport } from './routes/api/workflows/$id/executions.latest'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkflowsIndexRoute = AppWorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsIndexRoute = AppIntegrationsIndexRouteImport.update({
  id: '/integrations/',
  path: '/integrations/',
  getParentRoute: () => AppRoute,
} as any)
const AppCredentialsIndexRoute = AppCredentialsIndexRouteImport.update({
  id: '/credentials/',
  path: '/credentials/',
  getParentRoute: () => AppRoute,
} as any)
const ApiWorkflowsIndexRoute = ApiWorkflowsIndexRouteImport.update({
  id: '/api/workflows/',
  path: '/api/workflows/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCredentialsIndexRoute = ApiCredentialsIndexRouteImport.update({
  id: '/api/credentials/',
  path: '/api/credentials/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkflowIdRoute = AppWorkflowIdRouteImport.update({
  id: '/app_/workflow/$id',
  path: '/app/workflow/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkflowLayoutRoute = AppWorkflowLayoutRouteImport.update({
  id: '/workflow/_layout',
  path: '/workflow',
  getParentRoute: () => AppRoute,
} as any)
const ApiIntegrationsStatusRoute = ApiIntegrationsStatusRouteImport.update({
  id: '/api/integrations/status',
  path: '/api/integrations/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCredentialsIdRoute = ApiCredentialsIdRouteImport.update({
  id: '/api/credentials/$id',
  path: '/api/credentials/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkflowsIdIndexRoute = ApiWorkflowsIdIndexRouteImport.update({
  id: '/api/workflows/$id/',
  path: '/api/workflows/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkflowsIdTestRoute = ApiWorkflowsIdTestRouteImport.update({
  id: '/api/workflows/$id/test',
  path: '/api/workflows/$id/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksTallyWorkflowIdRoute =
  ApiWebhooksTallyWorkflowIdRouteImport.update({
    id: '/api/webhooks/tally/$workflowId',
    path: '/api/webhooks/tally/$workflowId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWebhooksGenericWorkflowIdRoute =
  ApiWebhooksGenericWorkflowIdRouteImport.update({
    id: '/api/webhooks/generic/$workflowId',
    path: '/api/webhooks/generic/$workflowId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsSlackDisconnectRoute =
  ApiIntegrationsSlackDisconnectRouteImport.update({
    id: '/api/integrations/slack/disconnect',
    path: '/api/integrations/slack/disconnect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsSlackConnectRoute =
  ApiIntegrationsSlackConnectRouteImport.update({
    id: '/api/integrations/slack/connect',
    path: '/api/integrations/slack/connect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsSlackChannelsRoute =
  ApiIntegrationsSlackChannelsRouteImport.update({
    id: '/api/integrations/slack/channels',
    path: '/api/integrations/slack/channels',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsSlackCallbackRoute =
  ApiIntegrationsSlackCallbackRouteImport.update({
    id: '/api/integrations/slack/callback',
    path: '/api/integrations/slack/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsDiscordGuildsRoute =
  ApiIntegrationsDiscordGuildsRouteImport.update({
    id: '/api/integrations/discord/guilds',
    path: '/api/integrations/discord/guilds',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsDiscordDisconnectRoute =
  ApiIntegrationsDiscordDisconnectRouteImport.update({
    id: '/api/integrations/discord/disconnect',
    path: '/api/integrations/discord/disconnect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsDiscordConnectRoute =
  ApiIntegrationsDiscordConnectRouteImport.update({
    id: '/api/integrations/discord/connect',
    path: '/api/integrations/discord/connect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsDiscordChannelsRoute =
  ApiIntegrationsDiscordChannelsRouteImport.update({
    id: '/api/integrations/discord/channels',
    path: '/api/integrations/discord/channels',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiIntegrationsDiscordCallbackRoute =
  ApiIntegrationsDiscordCallbackRouteImport.update({
    id: '/api/integrations/discord/callback',
    path: '/api/integrations/discord/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCredentialsIdTestRoute = ApiCredentialsIdTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => ApiCredentialsIdRoute,
} as any)
const ApiWorkflowsIdExecutionsLatestRoute =
  ApiWorkflowsIdExecutionsLatestRouteImport.update({
    id: '/api/workflows/$id/executions/latest',
    path: '/api/workflows/$id/executions/latest',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/credentials/$id': typeof ApiCredentialsIdRouteWithChildren
  '/api/integrations/status': typeof ApiIntegrationsStatusRoute
  '/app/workflow': typeof AppWorkflowLayoutRoute
  '/app/workflow/$id': typeof AppWorkflowIdRoute
  '/api/credentials/': typeof ApiCredentialsIndexRoute
  '/api/workflows/': typeof ApiWorkflowsIndexRoute
  '/app/credentials/': typeof AppCredentialsIndexRoute
  '/app/integrations/': typeof AppIntegrationsIndexRoute
  '/app/workflows/': typeof AppWorkflowsIndexRoute
  '/api/credentials/$id/test': typeof ApiCredentialsIdTestRoute
  '/api/integrations/discord/callback': typeof ApiIntegrationsDiscordCallbackRoute
  '/api/integrations/discord/channels': typeof ApiIntegrationsDiscordChannelsRoute
  '/api/integrations/discord/connect': typeof ApiIntegrationsDiscordConnectRoute
  '/api/integrations/discord/disconnect': typeof ApiIntegrationsDiscordDisconnectRoute
  '/api/integrations/discord/guilds': typeof ApiIntegrationsDiscordGuildsRoute
  '/api/integrations/slack/callback': typeof ApiIntegrationsSlackCallbackRoute
  '/api/integrations/slack/channels': typeof ApiIntegrationsSlackChannelsRoute
  '/api/integrations/slack/connect': typeof ApiIntegrationsSlackConnectRoute
  '/api/integrations/slack/disconnect': typeof ApiIntegrationsSlackDisconnectRoute
  '/api/webhooks/generic/$workflowId': typeof ApiWebhooksGenericWorkflowIdRoute
  '/api/webhooks/tally/$workflowId': typeof ApiWebhooksTallyWorkflowIdRoute
  '/api/workflows/$id/test': typeof ApiWorkflowsIdTestRoute
  '/api/workflows/$id/': typeof ApiWorkflowsIdIndexRoute
  '/api/workflows/$id/executions/latest': typeof ApiWorkflowsIdExecutionsLatestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/credentials/$id': typeof ApiCredentialsIdRouteWithChildren
  '/api/integrations/status': typeof ApiIntegrationsStatusRoute
  '/app/workflow': typeof AppWorkflowLayoutRoute
  '/app/workflow/$id': typeof AppWorkflowIdRoute
  '/api/credentials': typeof ApiCredentialsIndexRoute
  '/api/workflows': typeof ApiWorkflowsIndexRoute
  '/app/credentials': typeof AppCredentialsIndexRoute
  '/app/integrations': typeof AppIntegrationsIndexRoute
  '/app/workflows': typeof AppWorkflowsIndexRoute
  '/api/credentials/$id/test': typeof ApiCredentialsIdTestRoute
  '/api/integrations/discord/callback': typeof ApiIntegrationsDiscordCallbackRoute
  '/api/integrations/discord/channels': typeof ApiIntegrationsDiscordChannelsRoute
  '/api/integrations/discord/connect': typeof ApiIntegrationsDiscordConnectRoute
  '/api/integrations/discord/disconnect': typeof ApiIntegrationsDiscordDisconnectRoute
  '/api/integrations/discord/guilds': typeof ApiIntegrationsDiscordGuildsRoute
  '/api/integrations/slack/callback': typeof ApiIntegrationsSlackCallbackRoute
  '/api/integrations/slack/channels': typeof ApiIntegrationsSlackChannelsRoute
  '/api/integrations/slack/connect': typeof ApiIntegrationsSlackConnectRoute
  '/api/integrations/slack/disconnect': typeof ApiIntegrationsSlackDisconnectRoute
  '/api/webhooks/generic/$workflowId': typeof ApiWebhooksGenericWorkflowIdRoute
  '/api/webhooks/tally/$workflowId': typeof ApiWebhooksTallyWorkflowIdRoute
  '/api/workflows/$id/test': typeof ApiWorkflowsIdTestRoute
  '/api/workflows/$id': typeof ApiWorkflowsIdIndexRoute
  '/api/workflows/$id/executions/latest': typeof ApiWorkflowsIdExecutionsLatestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/credentials/$id': typeof ApiCredentialsIdRouteWithChildren
  '/api/integrations/status': typeof ApiIntegrationsStatusRoute
  '/app/workflow/_layout': typeof AppWorkflowLayoutRoute
  '/app_/workflow/$id': typeof AppWorkflowIdRoute
  '/api/credentials/': typeof ApiCredentialsIndexRoute
  '/api/workflows/': typeof ApiWorkflowsIndexRoute
  '/app/credentials/': typeof AppCredentialsIndexRoute
  '/app/integrations/': typeof AppIntegrationsIndexRoute
  '/app/workflows/': typeof AppWorkflowsIndexRoute
  '/api/credentials/$id/test': typeof ApiCredentialsIdTestRoute
  '/api/integrations/discord/callback': typeof ApiIntegrationsDiscordCallbackRoute
  '/api/integrations/discord/channels': typeof ApiIntegrationsDiscordChannelsRoute
  '/api/integrations/discord/connect': typeof ApiIntegrationsDiscordConnectRoute
  '/api/integrations/discord/disconnect': typeof ApiIntegrationsDiscordDisconnectRoute
  '/api/integrations/discord/guilds': typeof ApiIntegrationsDiscordGuildsRoute
  '/api/integrations/slack/callback': typeof ApiIntegrationsSlackCallbackRoute
  '/api/integrations/slack/channels': typeof ApiIntegrationsSlackChannelsRoute
  '/api/integrations/slack/connect': typeof ApiIntegrationsSlackConnectRoute
  '/api/integrations/slack/disconnect': typeof ApiIntegrationsSlackDisconnectRoute
  '/api/webhooks/generic/$workflowId': typeof ApiWebhooksGenericWorkflowIdRoute
  '/api/webhooks/tally/$workflowId': typeof ApiWebhooksTallyWorkflowIdRoute
  '/api/workflows/$id/test': typeof ApiWorkflowsIdTestRoute
  '/api/workflows/$id/': typeof ApiWorkflowsIdIndexRoute
  '/api/workflows/$id/executions/latest': typeof ApiWorkflowsIdExecutionsLatestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/api/auth/$'
    | '/api/credentials/$id'
    | '/api/integrations/status'
    | '/app/workflow'
    | '/app/workflow/$id'
    | '/api/credentials/'
    | '/api/workflows/'
    | '/app/credentials/'
    | '/app/integrations/'
    | '/app/workflows/'
    | '/api/credentials/$id/test'
    | '/api/integrations/discord/callback'
    | '/api/integrations/discord/channels'
    | '/api/integrations/discord/connect'
    | '/api/integrations/discord/disconnect'
    | '/api/integrations/discord/guilds'
    | '/api/integrations/slack/callback'
    | '/api/integrations/slack/channels'
    | '/api/integrations/slack/connect'
    | '/api/integrations/slack/disconnect'
    | '/api/webhooks/generic/$workflowId'
    | '/api/webhooks/tally/$workflowId'
    | '/api/workflows/$id/test'
    | '/api/workflows/$id/'
    | '/api/workflows/$id/executions/latest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/api/auth/$'
    | '/api/credentials/$id'
    | '/api/integrations/status'
    | '/app/workflow'
    | '/app/workflow/$id'
    | '/api/credentials'
    | '/api/workflows'
    | '/app/credentials'
    | '/app/integrations'
    | '/app/workflows'
    | '/api/credentials/$id/test'
    | '/api/integrations/discord/callback'
    | '/api/integrations/discord/channels'
    | '/api/integrations/discord/connect'
    | '/api/integrations/discord/disconnect'
    | '/api/integrations/discord/guilds'
    | '/api/integrations/slack/callback'
    | '/api/integrations/slack/channels'
    | '/api/integrations/slack/connect'
    | '/api/integrations/slack/disconnect'
    | '/api/webhooks/generic/$workflowId'
    | '/api/webhooks/tally/$workflowId'
    | '/api/workflows/$id/test'
    | '/api/workflows/$id'
    | '/api/workflows/$id/executions/latest'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/api/auth/$'
    | '/api/credentials/$id'
    | '/api/integrations/status'
    | '/app/workflow/_layout'
    | '/app_/workflow/$id'
    | '/api/credentials/'
    | '/api/workflows/'
    | '/app/credentials/'
    | '/app/integrations/'
    | '/app/workflows/'
    | '/api/credentials/$id/test'
    | '/api/integrations/discord/callback'
    | '/api/integrations/discord/channels'
    | '/api/integrations/discord/connect'
    | '/api/integrations/discord/disconnect'
    | '/api/integrations/discord/guilds'
    | '/api/integrations/slack/callback'
    | '/api/integrations/slack/channels'
    | '/api/integrations/slack/connect'
    | '/api/integrations/slack/disconnect'
    | '/api/webhooks/generic/$workflowId'
    | '/api/webhooks/tally/$workflowId'
    | '/api/workflows/$id/test'
    | '/api/workflows/$id/'
    | '/api/workflows/$id/executions/latest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCredentialsIdRoute: typeof ApiCredentialsIdRouteWithChildren
  ApiIntegrationsStatusRoute: typeof ApiIntegrationsStatusRoute
  AppWorkflowIdRoute: typeof AppWorkflowIdRoute
  ApiCredentialsIndexRoute: typeof ApiCredentialsIndexRoute
  ApiWorkflowsIndexRoute: typeof ApiWorkflowsIndexRoute
  ApiIntegrationsDiscordCallbackRoute: typeof ApiIntegrationsDiscordCallbackRoute
  ApiIntegrationsDiscordChannelsRoute: typeof ApiIntegrationsDiscordChannelsRoute
  ApiIntegrationsDiscordConnectRoute: typeof ApiIntegrationsDiscordConnectRoute
  ApiIntegrationsDiscordDisconnectRoute: typeof ApiIntegrationsDiscordDisconnectRoute
  ApiIntegrationsDiscordGuildsRoute: typeof ApiIntegrationsDiscordGuildsRoute
  ApiIntegrationsSlackCallbackRoute: typeof ApiIntegrationsSlackCallbackRoute
  ApiIntegrationsSlackChannelsRoute: typeof ApiIntegrationsSlackChannelsRoute
  ApiIntegrationsSlackConnectRoute: typeof ApiIntegrationsSlackConnectRoute
  ApiIntegrationsSlackDisconnectRoute: typeof ApiIntegrationsSlackDisconnectRoute
  ApiWebhooksGenericWorkflowIdRoute: typeof ApiWebhooksGenericWorkflowIdRoute
  ApiWebhooksTallyWorkflowIdRoute: typeof ApiWebhooksTallyWorkflowIdRoute
  ApiWorkflowsIdTestRoute: typeof ApiWorkflowsIdTestRoute
  ApiWorkflowsIdIndexRoute: typeof ApiWorkflowsIdIndexRoute
  ApiWorkflowsIdExecutionsLatestRoute: typeof ApiWorkflowsIdExecutionsLatestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/workflows/': {
      id: '/app/workflows/'
      path: '/workflows'
      fullPath: '/app/workflows/'
      preLoaderRoute: typeof AppWorkflowsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/integrations/': {
      id: '/app/integrations/'
      path: '/integrations'
      fullPath: '/app/integrations/'
      preLoaderRoute: typeof AppIntegrationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/credentials/': {
      id: '/app/credentials/'
      path: '/credentials'
      fullPath: '/app/credentials/'
      preLoaderRoute: typeof AppCredentialsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/workflows/': {
      id: '/api/workflows/'
      path: '/api/workflows'
      fullPath: '/api/workflows/'
      preLoaderRoute: typeof ApiWorkflowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/credentials/': {
      id: '/api/credentials/'
      path: '/api/credentials'
      fullPath: '/api/credentials/'
      preLoaderRoute: typeof ApiCredentialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app_/workflow/$id': {
      id: '/app_/workflow/$id'
      path: '/app/workflow/$id'
      fullPath: '/app/workflow/$id'
      preLoaderRoute: typeof AppWorkflowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/workflow/_layout': {
      id: '/app/workflow/_layout'
      path: '/workflow'
      fullPath: '/app/workflow'
      preLoaderRoute: typeof AppWorkflowLayoutRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/integrations/status': {
      id: '/api/integrations/status'
      path: '/api/integrations/status'
      fullPath: '/api/integrations/status'
      preLoaderRoute: typeof ApiIntegrationsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/credentials/$id': {
      id: '/api/credentials/$id'
      path: '/api/credentials/$id'
      fullPath: '/api/credentials/$id'
      preLoaderRoute: typeof ApiCredentialsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/$id/': {
      id: '/api/workflows/$id/'
      path: '/api/workflows/$id'
      fullPath: '/api/workflows/$id/'
      preLoaderRoute: typeof ApiWorkflowsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/$id/test': {
      id: '/api/workflows/$id/test'
      path: '/api/workflows/$id/test'
      fullPath: '/api/workflows/$id/test'
      preLoaderRoute: typeof ApiWorkflowsIdTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/tally/$workflowId': {
      id: '/api/webhooks/tally/$workflowId'
      path: '/api/webhooks/tally/$workflowId'
      fullPath: '/api/webhooks/tally/$workflowId'
      preLoaderRoute: typeof ApiWebhooksTallyWorkflowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/generic/$workflowId': {
      id: '/api/webhooks/generic/$workflowId'
      path: '/api/webhooks/generic/$workflowId'
      fullPath: '/api/webhooks/generic/$workflowId'
      preLoaderRoute: typeof ApiWebhooksGenericWorkflowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/slack/disconnect': {
      id: '/api/integrations/slack/disconnect'
      path: '/api/integrations/slack/disconnect'
      fullPath: '/api/integrations/slack/disconnect'
      preLoaderRoute: typeof ApiIntegrationsSlackDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/slack/connect': {
      id: '/api/integrations/slack/connect'
      path: '/api/integrations/slack/connect'
      fullPath: '/api/integrations/slack/connect'
      preLoaderRoute: typeof ApiIntegrationsSlackConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/slack/channels': {
      id: '/api/integrations/slack/channels'
      path: '/api/integrations/slack/channels'
      fullPath: '/api/integrations/slack/channels'
      preLoaderRoute: typeof ApiIntegrationsSlackChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/slack/callback': {
      id: '/api/integrations/slack/callback'
      path: '/api/integrations/slack/callback'
      fullPath: '/api/integrations/slack/callback'
      preLoaderRoute: typeof ApiIntegrationsSlackCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/discord/guilds': {
      id: '/api/integrations/discord/guilds'
      path: '/api/integrations/discord/guilds'
      fullPath: '/api/integrations/discord/guilds'
      preLoaderRoute: typeof ApiIntegrationsDiscordGuildsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/discord/disconnect': {
      id: '/api/integrations/discord/disconnect'
      path: '/api/integrations/discord/disconnect'
      fullPath: '/api/integrations/discord/disconnect'
      preLoaderRoute: typeof ApiIntegrationsDiscordDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/discord/connect': {
      id: '/api/integrations/discord/connect'
      path: '/api/integrations/discord/connect'
      fullPath: '/api/integrations/discord/connect'
      preLoaderRoute: typeof ApiIntegrationsDiscordConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/discord/channels': {
      id: '/api/integrations/discord/channels'
      path: '/api/integrations/discord/channels'
      fullPath: '/api/integrations/discord/channels'
      preLoaderRoute: typeof ApiIntegrationsDiscordChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations/discord/callback': {
      id: '/api/integrations/discord/callback'
      path: '/api/integrations/discord/callback'
      fullPath: '/api/integrations/discord/callback'
      preLoaderRoute: typeof ApiIntegrationsDiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/credentials/$id/test': {
      id: '/api/credentials/$id/test'
      path: '/test'
      fullPath: '/api/credentials/$id/test'
      preLoaderRoute: typeof ApiCredentialsIdTestRouteImport
      parentRoute: typeof ApiCredentialsIdRoute
    }
    '/api/workflows/$id/executions/latest': {
      id: '/api/workflows/$id/executions/latest'
      path: '/api/workflows/$id/executions/latest'
      fullPath: '/api/workflows/$id/executions/latest'
      preLoaderRoute: typeof ApiWorkflowsIdExecutionsLatestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppWorkflowLayoutRoute: typeof AppWorkflowLayoutRoute
  AppCredentialsIndexRoute: typeof AppCredentialsIndexRoute
  AppIntegrationsIndexRoute: typeof AppIntegrationsIndexRoute
  AppWorkflowsIndexRoute: typeof AppWorkflowsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppWorkflowLayoutRoute: AppWorkflowLayoutRoute,
  AppCredentialsIndexRoute: AppCredentialsIndexRoute,
  AppIntegrationsIndexRoute: AppIntegrationsIndexRoute,
  AppWorkflowsIndexRoute: AppWorkflowsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ApiCredentialsIdRouteChildren {
  ApiCredentialsIdTestRoute: typeof ApiCredentialsIdTestRoute
}

const ApiCredentialsIdRouteChildren: ApiCredentialsIdRouteChildren = {
  ApiCredentialsIdTestRoute: ApiCredentialsIdTestRoute,
}

const ApiCredentialsIdRouteWithChildren =
  ApiCredentialsIdRoute._addFileChildren(ApiCredentialsIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCredentialsIdRoute: ApiCredentialsIdRouteWithChildren,
  ApiIntegrationsStatusRoute: ApiIntegrationsStatusRoute,
  AppWorkflowIdRoute: AppWorkflowIdRoute,
  ApiCredentialsIndexRoute: ApiCredentialsIndexRoute,
  ApiWorkflowsIndexRoute: ApiWorkflowsIndexRoute,
  ApiIntegrationsDiscordCallbackRoute: ApiIntegrationsDiscordCallbackRoute,
  ApiIntegrationsDiscordChannelsRoute: ApiIntegrationsDiscordChannelsRoute,
  ApiIntegrationsDiscordConnectRoute: ApiIntegrationsDiscordConnectRoute,
  ApiIntegrationsDiscordDisconnectRoute: ApiIntegrationsDiscordDisconnectRoute,
  ApiIntegrationsDiscordGuildsRoute: ApiIntegrationsDiscordGuildsRoute,
  ApiIntegrationsSlackCallbackRoute: ApiIntegrationsSlackCallbackRoute,
  ApiIntegrationsSlackChannelsRoute: ApiIntegrationsSlackChannelsRoute,
  ApiIntegrationsSlackConnectRoute: ApiIntegrationsSlackConnectRoute,
  ApiIntegrationsSlackDisconnectRoute: ApiIntegrationsSlackDisconnectRoute,
  ApiWebhooksGenericWorkflowIdRoute: ApiWebhooksGenericWorkflowIdRoute,
  ApiWebhooksTallyWorkflowIdRoute: ApiWebhooksTallyWorkflowIdRoute,
  ApiWorkflowsIdTestRoute: ApiWorkflowsIdTestRoute,
  ApiWorkflowsIdIndexRoute: ApiWorkflowsIdIndexRoute,
  ApiWorkflowsIdExecutionsLatestRoute: ApiWorkflowsIdExecutionsLatestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
