/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkflowsIndexRouteImport } from './routes/workflows/index'
import { Route as WorkflowIdRouteImport } from './routes/workflow/$id'
import { Route as ApiWorkflowsIndexRouteImport } from './routes/api/workflows/index'
import { Route as ApiWorkflowsIdRouteImport } from './routes/api/workflows/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIndexRoute = WorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowIdRoute = WorkflowIdRouteImport.update({
  id: '/workflow/$id',
  path: '/workflow/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkflowsIndexRoute = ApiWorkflowsIndexRouteImport.update({
  id: '/api/workflows/',
  path: '/api/workflows/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkflowsIdRoute = ApiWorkflowsIdRouteImport.update({
  id: '/api/workflows/$id',
  path: '/api/workflows/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workflow/$id': typeof WorkflowIdRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/workflows/$id': typeof ApiWorkflowsIdRoute
  '/api/workflows/': typeof ApiWorkflowsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/workflow/$id': typeof WorkflowIdRoute
  '/workflows': typeof WorkflowsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/workflows/$id': typeof ApiWorkflowsIdRoute
  '/api/workflows': typeof ApiWorkflowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/workflow/$id': typeof WorkflowIdRoute
  '/workflows/': typeof WorkflowsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/workflows/$id': typeof ApiWorkflowsIdRoute
  '/api/workflows/': typeof ApiWorkflowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/workflow/$id'
    | '/workflows/'
    | '/api/auth/$'
    | '/api/workflows/$id'
    | '/api/workflows/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/workflow/$id'
    | '/workflows'
    | '/api/auth/$'
    | '/api/workflows/$id'
    | '/api/workflows'
  id:
    | '__root__'
    | '/'
    | '/workflow/$id'
    | '/workflows/'
    | '/api/auth/$'
    | '/api/workflows/$id'
    | '/api/workflows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkflowIdRoute: typeof WorkflowIdRoute
  WorkflowsIndexRoute: typeof WorkflowsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiWorkflowsIdRoute: typeof ApiWorkflowsIdRoute
  ApiWorkflowsIndexRoute: typeof ApiWorkflowsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/': {
      id: '/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof WorkflowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow/$id': {
      id: '/workflow/$id'
      path: '/workflow/$id'
      fullPath: '/workflow/$id'
      preLoaderRoute: typeof WorkflowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/': {
      id: '/api/workflows/'
      path: '/api/workflows'
      fullPath: '/api/workflows/'
      preLoaderRoute: typeof ApiWorkflowsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflows/$id': {
      id: '/api/workflows/$id'
      path: '/api/workflows/$id'
      fullPath: '/api/workflows/$id'
      preLoaderRoute: typeof ApiWorkflowsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkflowIdRoute: WorkflowIdRoute,
  WorkflowsIndexRoute: WorkflowsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiWorkflowsIdRoute: ApiWorkflowsIdRoute,
  ApiWorkflowsIndexRoute: ApiWorkflowsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
